### ISSUE TITLE
acceleration array of size 4?

### ISSUE THREAD

**Issue by jdrehobl** [KalebKE/GyroscopeExplorer#25]
Why is "private float[] acceleration = new float[4]" size 4 instead of 3? From https://developer.android.com/reference/android/hardware/SensorEvent, it looks like it should be size 3? Changing it to size 3 doesn't seem to change anything, but just seems more correct, even if having it as 4 doesn't appear to be causing any issues?

**Comment by KalebKE** [comment]
Hi @jdrehobl 

I apologize for the late reply. I didn't see the issue get opened.

The extra index has been used to store a timestamp in the past. As I recall, I made some changes in FSensor that no longer requires the extra timestamp. Looking at the code, changing it to a size of three should be fine since it uses the size of the array provided by SensorEvent to copy the array.
