### ISSUE TITLE
Roll values when device is flat vs upright

### ISSUE THREAD

**Issue by CreaRo** [KalebKE/GyroscopeExplorer#6]
I've been trying sensor-fusion for the past couple of days -- I made a very simple implementation based on Paul Lawitski's complimentary filter. All works great when the device is flat. 

As soon as I bring the device upright, roll values go for a toss; the problem is the call to `calculateAccMagOrientation()` which internally calls `getRotationMatrix()` and `getOrientation()`. The rotation matrix returned is in the NEG axes (North, East, Ground). These align when the device is flat, but change when device is made upright. This results in bizarre roll and yaw values. A quick fix is to use `SensorManager.remapCoordinateSystem()`, but this is outright hacky. 

Paul L.'s code suffers the same problem. All's great when flat, but the roll&yaw values mess up when device is straight. I haven't been able to explore your code entirely, but does your app not suffer the same issue as it is based off of Paul L.'s code?

**Comment by KalebKE** [comment]
I have deprecated the Euler based fusions in favor of the Quaternions because they are more stable. GyroscopeExplorer is now backed by [FSensor](https://github.com/KalebKE/FSensor) which implements two flavors of the Quaternion based fusions, Complimentary and Kalman.

I find the Complimentary fusion to be especially stable. Please try FSensor and report any issues there.
